name: Android Ci Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
          cache: gradle

      - name: Build with Gradle Canary
        shell: bash
        run: ./gradlew assembleCanary

      - name: Sign Canary APK
        if: success()
        id: sign_canary
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: ./app/build/outputs/apk/canary
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Upload Canary APK
        if: contains(github.event.head_commit.message, '[upload]') == true
        uses: actions/upload-artifact@v3
        with:
          name: Cemiuiler canary
          path: ${{ steps.sign_canary.outputs.signedReleaseFile }}
